### ISSUE TITLE
[QUESTION] WYSIWYG editor with hierarchical file organization

### ISSUE THREAD

**Issue by Luiz-nyan** [JefMari/awesome-wysiwyg-editors#62]
Firstly, congratulations on the great work, it really helps a lot.

Do you know of any WYSIWYG that is installable on the Operating System and that has a hierarchical file organization similar to some IDEs such as IntelliJ IDEA, VSCode etc.
It doesn't necessarily need to be an installer, it can be online too, but it has this tree organization function. I found something similar in Adobe DreamWaver, but I simply need WYSIWYG + tree organization

**Comment by JefMari** [comment]
Hi @Luiz-nyan !

Thank you very much for your wonderful words! I'm delighted to hear that you found the material useful here.

as for your question, try checking out **TinyMCE**.

**Comment by JefMari** [comment]
I'm closing this issue because it appears to have been resolved.
