### ISSUE TITLE
A WYSIWYG Editor for HTML with webcomponents

### ISSUE THREAD

**Issue by jogibear9988** [JefMari/awesome-wysiwyg-editors#67]
see:
https://node-projects.github.io/web-component-designer-demo/index.html

it's a editor to use webcomponents, the editor itself is a webcomponent

**Comment by JefMari** [comment]
Hi @jogibear9988 ,

Nice project, please make a pull request about it.

Thanks~!

**Comment by jogibear9988** [comment]
here: https://github.com/JefMari/awesome-wysiwyg-editors/pull/68

**Comment by jogibear9988** [comment]
@JefMari do I miss something, or is the pull req okay?

**Comment by JefMari** [comment]
All goods @jogibear9988 ! Thanks!
