### ISSUE TITLE
Please Add Umo Editor

### ISSUE THREAD

**Issue by umodoc** [JefMari/awesome-wysiwyg-editors#70]
Umo Editor is a localized open-source document editor suitable for Chinese users, based on Vue3.
Github: https://github.com/umodoc/editor

**Comment by JefMari** [comment]
hi @umodoc , 

Nice project! Can we have an English Translation of Docs for this? 

Thanks!

**Comment by umodoc** [comment]
> hi @umodoc ,
> 
> Nice project! Can we have an English Translation of Docs for this?
> 
> Thanks!

Hi, @JefMari v2.0.0,

Thank you for your kind words and interest in our project! We're glad to hear that you find Umo Editor valuable.

We're pleased to inform you that starting from version 2.0.0, Umo Editor does indeed support English language documentation. You can access the English documentation at the following link: [Umo Editor English Documentation](https://editor.umodoc.com/en/docs).

We welcome any suggestions you may have regarding the translation or any other aspect of the documentation. If you're inclined to contribute, we would be grateful for any Pull Requests (PRs) that you could submit to improve the documentation further.

Feel free to reach out if you have any questions or need assistance with the translation process.

Best regards,
umodoc

**Comment by JefMari** [comment]
Hi @umodoc ,

Nice! I think it’s good to add it to the list. Can you make a PR for it?

Thanks!

**Comment by umodoc** [comment]
> Hi @umodoc ,
> 
> Nice! I think it’s good to add it to the list. Can you make a PR for it?
> 
> Thanks!

@JefMari I have submitted a PR #72, please merge it.

Thanks!

**Comment by JefMari** [comment]
Cool! You even add it into CN docs! Thanks!
